app:
  host: "0.0.0.0"
  port: 8000
  debug: true

logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: 'logs/app.log'

data:
  upload_folder: 'data/uploads'
  export_folder: 'data/exports'
  temp_folder: 'data/temp'
  results_folder: 'data/results'
  plots_folder: 'static/plots'
  allowed_extensions:
    - '.csv'
    - '.xlsx'
    - '.xls'
  max_file_size_mb: 200

validation:
  missing_threshold: 0.2  # Maximum allowed percentage of missing values
  correlation_threshold: 0.8  # Threshold for high correlation warning
  outlier_sensitivity:
    z_score: 3
    iqr: 1.5

  range_validation:
    column1: # Example column name, replace with actual column names
      min: 0    # Minimum allowed value
      max: 100  # Maximum allowed value
    column2:
      min: -50
      max: 50
