app:
  host: "0.0.0.0"
  port: 8000
  debug: true

logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: 'logs/app.log'

data:
  upload_folder: 'data/uploads'
  export_folder: 'data/exports'
  allowed_extensions:
    - '.csv'
    - '.xlsx'
    - '.xls'
  max_file_size_mb: 200

validation:
  missing_threshold: 0.2  # Maximum allowed percentage of missing values
  correlation_threshold: 0.8  # Threshold for high correlation warning
